### ISSUE TITLE
[🐛] [App Crash] On Rendering Banner Ads

### ISSUE THREAD

**Issue by cw-sanjeev** [invertase/react-native-google-mobile-ads#402]
### What happened?

We are using this library to render banner ads.
For some reason we are facing a crash that says context is null when initializing the view.
Crash Log:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Context.isUiContext()' on a null object reference
       at android.view.ViewConfiguration.get(ViewConfiguration.java:507)
       at android.view.View.<init>(View.java:5356)
       at android.view.View.<init>(View.java:5518)
       at android.view.ViewGroup.<init>(ViewGroup.java:708)
       at android.view.ViewGroup.<init>(ViewGroup.java:704)
       at android.view.ViewGroup.<init>(ViewGroup.java:700)
       at android.view.ViewGroup.<init>(ViewGroup.java:696)
       at com.facebook.react.views.view.ReactViewGroup.<init>(ReactViewGroup.java:132)
       at io.invertase.googlemobileads.common.ReactNativeAdView.<init>(ReactNativeAdView.java:19)
       at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsBannerAdViewManager.createViewInstance(ReactNativeGoogleMobileAdsBannerAdViewManager.java:68)
       at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsBannerAdViewManager.createViewInstance(ReactNativeGoogleMobileAdsBannerAdViewManager.java:48)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:188)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:902)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1019)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:977)
       at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8010)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

### Platforms

Only on Android

### React Native Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 2.19 GB / 15.71 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-222.4459.24.2221.10121639
    Visual Studio: Not Found
  Languages:
    Java: 16.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.11 => 0.71.11
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```JSON
{
  "name": "",
  "version": "1.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "android": "node node_modules/react-native-cli/index.js run-android",
    "flow": "flow",
    "flow-stop": "flow stop",
    "lint": "eslint .",
    "postinstall": "npx jetify",
    "test": "jest",
    "testcoverage": "jest --coverage",
    "updateSnapshots": "jest --updateSnapshot",
    "initcodepushhelper": "node ./codepushhelpercli/index.js"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts"
    ]
  },
  "dependencies": {
    "@babel/plugin-proposal-decorators": "7.21.0",
    "@nozbe/watermelondb": "0.25.5",
    "@react-native-async-storage/async-storage": "1.17.12",
    "@react-native-community/masked-view": "0.1.11",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-firebase/app": "17.4.2",
    "@react-native-firebase/analytics": "17.4.2",
    "@react-native-firebase/crashlytics": "17.4.2",
    "@react-native-firebase/perf": "17.4.2",
    "@react-native-firebase/installations": "17.4.2",
    "@react-native-firebase/remote-config": "17.4.2",
    "@react-native/normalize-color": "2.1.0",
    "@react-navigation/bottom-tabs": "6.0.9",
    "@react-navigation/drawer": "6.5.0",
    "@react-navigation/native": "6.1.6",
    "@react-navigation/native-stack": "6.9.12",
    "@shopify/flash-list": "1.4.1",
    "d3-shape": "3.0.1",
    "enzyme": "3.11.0",
    "enzyme-adapter-react-16": "1.15.6",
    "enzyme-react-16-adapter-setup": "0.1.0",
    "hashmap": "2.3.0",
    "intl": "1.2.5",
    "jsc-android": "250231.0.0",
    "lodash": "4.17.21",
    "prop-types": "15.7.2",
    "react": "18.2.0",
    "react-native": "0.71.11",
    "react-native-autoheight-webview": "1.6.4",
    "react-native-blob-util": "0.18.2",
    "react-native-code-push": "8.0.2",
    "react-native-elements": "3.4.1",
    "react-native-form-validator": "0.3.5",
    "react-native-geolocation-service": "5.3.1",
    "react-native-gesture-handler": "2.9.0",
    "react-native-google-mobile-ads": "10.0.1",
    "react-native-image-picker": "4.8.5",
    "react-native-intersection-observer": "0.0.9",
    "react-native-keyboard-aware-scroll-view": "0.9.4",
    "react-native-linear-gradient": "2.6.2",
    "react-native-orientation-locker": "1.5.0",
    "react-native-pager-view": "6.1.4",
    "react-native-network-logger": "1.13.0",
    "react-native-permissions": "3.0.5",
    "react-native-pie": "0.5.0",
    "react-native-reanimated": "2.15.0",
    "react-native-safe-area-context": "4.5.3",
    "react-native-screens": "3.20.0",
    "react-native-share": "8.2.0",
    "react-native-star-rating": "1.1.0",
    "react-native-svg": "13.9.0",
    "react-native-svg-charts": "5.4.0",
    "react-native-vector-icons": "8.1.0",
    "react-native-webview": "11.23.1",
    "react-navigation": "4.4.4",
    "react-navigation-stack": "2.10.4",
    "react-navigation-tabs": "2.11.1",
    "react-redux": "8.0.7",
    "recyclerlistview": "4.2.0",
    "redux": "4.2.1",
    "redux-logger": "3.0.6",
    "redux-persist": "6.0.0",
    "redux-thunk": "2.4.2",
    "scheduler": "0.23.0",
    "styled-components": "3.4.1"
  },
  "devDependencies": {
    "@babel/core": "7.22.1",
    "@babel/preset-env": "7.22.4",
    "@babel/runtime": "7.22.3",
    "@jest/create-cache-key-function": "26.5.0",
    "@react-native-community/eslint-config": "3.2.0",
    "@testing-library/react-native": "7.2.0",
    "@tsconfig/react-native": "2.0.2",
    "@types/jest": "29.2.1",
    "@types/react": "18.0.24",
    "@types/react-native": "0.71.3",
    "@types/react-test-renderer": "18.0.0",
    "@types/styled-components": "4.0.3",
    "babel-eslint": "8.2.3",
    "babel-jest": "29.2.1",
    "babel-plugin-module-resolver": "3.1.3",
    "enzyme-to-json": "3.6.2",
    "eslint": "8.19.0",
    "eslint-config-airbnb": "16.1.0",
    "eslint-plugin-import": "2.12.0",
    "eslint-plugin-jsx-a11y": "6.0.3",
    "eslint-plugin-react": "7.8.2",
    "flow-bin": "0.73.0",
    "jest": "29.2.1",
    "jest-enzyme": "7.1.2",
    "jetifier": "1.6.4",
    "metro-react-native-babel-preset": "0.73.10",
    "react-dom": "17.0.1",
    "react-test-renderer": "18.2.0",
    "redux-mock-store": "1.5.4",
    "prettier": "2.4.1",
    "typescript": "4.8.4"
  }
}

```
```


### app.json

```JSON
{
   "name":"APP_NAME",
   "displayName":"APP_NAME",
   "react-native-google-mobile-ads":{
      "android_app_id":"ANDROID_AD_ID",
      "optimize_initialization":true,
      "optimize_ad_loading":true,
      "delay_app_measurement_init":false
   }
}
```
```


### ios/Podfile

_No response_

### android/build.gradle


### android/app/build.gradle

_No response_

### android/settings.gradle

_No response_

### AndroidManifest.xml

_No response_

**Comment by mikehardy** [comment]
Very strange. Are you able to supply a scenario that reproduces this reliably?

Looks like it's coming from this line, but note that the argument is specified as `@NonNull`:

https://github.com/invertase/react-native-google-mobile-ads/blob/ab55792673b732f84eeb772a2626d0dc50b85a50/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java#L70

Which implies that some calling piece of code is breaking their contract if they are supplying a null context
I'm not sure how to mitigate that as our API contract specifies that we are unable to catch the exception and reply with a null...

Not sure what other mitigations there are. Perhaps attempt to grab the application context in some other way?

I won't have time to troubleshoot this but I believe I have pointed into the code where the problem is. Through some combination of trying things there while searching stackoverflow + patch-package you may be able to come up with a solution ?

**Comment by cw-sanjeev** [comment]
@mikehardy I am not able to repro this under normal circumstances, although when I toggle my `Don't keep activities` flag in developers option and open my app and close quickly, this crash is getting logged.

**Comment by CW-RanjitMahadik** [comment]
@mikehardy we tried updating the lib to it's latest version(11.1.1) and now we are getting following crash.
```
Fatal Exception: java.lang.NullPointerException:
       at java.util.Objects.requireNonNull(Objects.java:220)
       at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsBannerAdViewManager.initAdView(ReactNativeGoogleMobileAdsBannerAdViewManager.java:165)
       at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsBannerAdViewManager.requestAd(ReactNativeGoogleMobileAdsBannerAdViewManager.java:248)
       at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsBannerAdViewManager.onAfterUpdateTransaction(ReactNativeGoogleMobileAdsBannerAdViewManager.java:144)
       at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsBannerAdViewManager.onAfterUpdateTransaction(ReactNativeGoogleMobileAdsBannerAdViewManager.java:50)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:88)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:188)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:115)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:909)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:984)
       at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:30)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7697)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

which is occurring because of following line.

https://github.com/invertase/react-native-google-mobile-ads/blob/ab55792673b732f84eeb772a2626d0dc50b85a50/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java#L165

`((ReactContext) reactViewGroup.getContext()).getCurrentActivity()` this statement results in null.

this happens when requestAd method get's called and after which app is killed which results in context being null.

To prevent the crash, we've added a check to verify if activity is available or not but we are not sure about this is correct way to handle it.

https://github.com/invertase/react-native-google-mobile-ads/blob/ab55792673b732f84eeb772a2626d0dc50b85a50/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java#L244

```
 if (sizes == null || unitId == null || request == null || manualImpressionsEnabled == null || ((ReactContext) reactViewGroup.getContext()).getCurrentActivity() == null) {
      return;
    }
```
