### ISSUE TITLE
 ERROR Invariant Violation: requireNativeComponent: "RNGoogleMobileAdsBannerView" was not found in the UIManager.

### ISSUE THREAD

**Issue by chris783** [invertase/react-native-google-mobile-ads#407]
### What happened?

ERROR  Invariant Violation: requireNativeComponent: "RNGoogleMobileAdsBannerView" was not found in the UIManager.

This error is located at:
    in RNGoogleMobileAdsBannerView (created by BaseAd)
    in BaseAd (created by BannerAd)
    in BannerAd (created by LuckyAdds)
    in LuckyAdds (created by Predictions)
    in RCTView (created by View)
    in View (created by Predictions)
    in RCTView (created by View)
    in View (created by Predictions)
    in Predictions (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by Drawer)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by Drawer)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by Drawer)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by Drawer)
    in RCTView (created by View)
    in View (created by Drawer)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by Drawer)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by Drawer)
    in Drawer (created by DrawerViewBase)
    in DrawerViewBase (created by DrawerView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by DrawerView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by DrawerView)
    in DrawerView (created by DrawerNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by DrawerNavigator)
    in DrawerNavigator (created by DrawerNavigator)
    in DrawerNavigator (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
 WARN  Possible Unhandled Promise Rejection (id: 0):
Invariant Violation: requireNativeComponent: "RNGoogleMobileAdsBannerView" was not found in the UIManager.
Invariant Violation: requireNativeComponent: "RNGoogleMobileAdsBannerView" was not found in the UIManager.
    at invariant (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:2574:26)
    at getNativeComponentAttributes (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:11702:14)
    at anonymous (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:65068:42)
    at anonymous (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:11203:28)
    at createInstance (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:86096:46)
    at completeWork (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:94800:48)
    at completeUnitOfWork (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:98037:34)
    at performUnitOfWork (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:98013:29)
    at workLoopSync (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:97939:28)
    at renderRootSync (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:97916:25)
    at performSyncWorkOnRoot (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:97641:40)
    at flushSyncCallbacks (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:86833:36)
    at flushSyncCallbacksOnlyInLegacyMode (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:86815:29)
    at scheduleUpdateOnFiber (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:97202:47)
    at dispatchSetState (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:90962:34)
    at ?anon_0_ (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:190146:22)
    at next (native)
    at asyncGeneratorStep (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:6090:26)
    at _next (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:6109:29)
    at tryCallOne (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1f3s36z5/x86_64/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1f3s36z5/x86_64/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:39595:26)
    at _callTimer (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:39474:17)
    at _callReactNativeMicrotasksPass (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:39519:17)
    at callReactNativeMicrotasks (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:39725:44)
    at __callReactNativeMicrotasks (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3696:46)
    at anonymous (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3470:45)
    at __guard (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3669:15)
    at flushedQueue (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3469:21)
    at callFunctionReturnFlushedQueue (http://192.168.100.15:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3454:33)

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```Shell
None, using expo
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
{
  "name": "name",
  "version": "1.0.1",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "babel-plugin-transform-remove-imports": "^1.7.0"
  },
  "private": true,
  "dependencies": {
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "axios": "^1.4.0",
    "expo": "^49.0.2",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "~0.18.9",
    "react": "18.2.0",
    "react-native": "0.72.1",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-google-mobile-ads": "^11.1.1",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "expo-dev-client": "~2.4.5"
  }
}
```

### app.json

```JSON
{
  "expo": {
    "name": "xxx",
    "slug": "xxx",
    "scheme": "development",
    "version": "1.0.3",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0,
      "url": "https://u.expo.dev/xxx"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "buildNumber": "1.0.3"
    },
    "android": {
      "versionCode": 5,
      "adaptiveIcon": {
        "foregroundImage": "./assets/splash.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "xxx"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "xxx"
      }
    },
    "runtimeVersion": {
      "policy": "sdkVersion"
    }
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "xxxxx",
    "ios_app_id": "xxxxxx"
  }
}
```

### ios/Podfile

```Ruby
None, using expo
```

### android/build.gradle

```Groovy
None, using expo
```

### android/app/build.gradle

```Groovy
None, using expo
```

### android/settings.gradle

```Groovy
None, using expo
```

### AndroidManifest.xml

```XML
None, using expo
```

**Comment by Kaosc** [comment]
Did you rebuild your app after installed the package ?

**Comment by morishin** [comment]
Same error

**Comment by dylancom** [comment]
Please follow the docs and use `npx expo prebuild`.

**Comment by morishin** [comment]
Thanks. We need prebuilding with eas-cli.
https://docs.page/invertase/react-native-google-mobile-ads#setting-up-google-admob

**Comment by chhavaibhav** [comment]
Similar error?
Any one got the solution?
