### ISSUE TITLE
[🐛] Bug Report Title - Unable to build android app v14.0.0

### ISSUE THREAD

**Issue by claudiofus** [invertase/react-native-google-mobile-ads#605]
### What happened?

I'm trying to build an android app with managed Expo but I have this problem that blocks building process. This problem occurred both locally and with EAS build.

```
/home/expo/workingdir/build/core/node_modules/react-native-google-mobile-ads/android/src/main/java/io/invertase/googlemobileads/common/ReactNativeModule.java:69: warning: [removal] onCatalystInstanceDestroy() in NativeModule has been deprecated and marked for removal
public void onCatalystInstanceDestroy() {
^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/expo/workingdir/build/core/node_modules/react-native-google-mobile-ads/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsCommon.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
```

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```Shell
---
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "check-upgrade": "npx expo install --check",
    "local-build-ios": "eas build -p ios --profile prof-san --clear-cache --local && eas submit -p ios"
  },
  "dependencies": {
    "@expo/metro-config": "~0.18.1",
    "@expo/ngrok": "^4.1.1",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-masked-view/masked-view": "0.3.1",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.20",
    "expo": "~51.0.20",
    "expo-build-properties": "~0.12.3",
    "expo-constants": "~16.0.2",
    "expo-dev-client": "~4.0.20",
    "expo-device": "~6.0.2",
    "expo-linear-gradient": "~13.0.2",
    "expo-linking": "~6.3.1",
    "expo-splash-screen": "~0.27.5",
    "expo-store-review": "~7.0.2",
    "firebase": "^10.6.0",
    "prop-types": "^15.8.1",
    "react": "18.2.0",
    "react-native": "0.74.3",
    "react-native-chart-kit": "^6.12.0",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-google-mobile-ads": "^14.0.0",
    "react-native-purchases": "7.28.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-svg": "15.2.0",
    "sentry-expo": "~7.0.0"
  },
  "devDependencies": {
    "babel-preset-expo": "~11.0.0",
    "eslint-config-handlebarlabs": "^0.0.6",
    "prettier": "^3.1.0",
    "react-devtools": "^4.28.5",
    "react-native-debugger": "^1.1.0"
  },
  "private": true
}
```

### app.json

```JSON
{
  "expo": {
    "name": "Problemi di Matematica",
    "slug": "Problemi_di_Matematica",
    "privacy": "hidden",
    "jsEngine": "hermes",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "2.0.3",
    "assetBundlePatterns": [
      "**/*"
    ],
    "plugins": [
      "sentry-expo",
      [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 34,
            "targetSdkVersion": 34,
            "minSdkVersion": 24
          }
        }
      ]
    ],
    "android": {
      "package": "com.xxx.xxx",
      "versionCode": 36,
      "permissions": []
    },
    "ios": {
      "bundleIdentifier": "com.xxx.xxx",
      "buildNumber": "2.0.3",
      "infoPlist": {
        "NSUserTrackingUsageDescription": "Questo consenso verrà utilizzato per mostrare banner pubblicitari personalizzati.",
        "CFBundleDevelopmentRegion": "it"
      },
      "supportsTablet": true
    },
    "description": ""
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-xxx",
    "ios_app_id": "ca-app-pub-xxx",
    "user_tracking_usage_description": "Questo consenso verrà utilizzato per mostrare banner pubblicitari personalizzati."
  }
}
```

**Comment by dylancom** [comment]
Thanks for the report. Fixed in 14.0.1.

**Comment by claudiofus** [comment]
Thank you, now I'm able to create a build but I have this problem on splashscreen, same configuration of above expect
`"react-native-google-mobile-ads": "^14.0.1"`

```
FATAL EXCEPTION: main
	Process: com.xxx.xxxx, PID: 20570
	java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
	
	******************************************************************************
	* Invalid application ID. Follow instructions here:                          *
	* https://googlemobileadssdk.page.link/admob-android-update-manifest         *
	* to find your app ID.                                                       *
	* Google Ad Manager publishers should follow instructions here:              *
	* https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
	******************************************************************************
	
	
		at android.app.ActivityThread.installProvider(ActivityThread.java:8489)
		at android.app.ActivityThread.installContentProviders(ActivityThread.java:7989)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7675)
		at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
		at android.os.Handler.dispatchMessage(Handler.java:106)
		at android.os.Looper.loopOnce(Looper.java:230)
		at android.os.Looper.loop(Looper.java:319)
		at android.app.ActivityThread.main(ActivityThread.java:8919)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by dylancom** [comment]
Please read the updated docs on expo (since 14.0.0). You should add your app ids to plugins. We have added a config plugin.
